*Análisis preliminar*

***1. Importaciones***

In [9]:
#Importamos pandas
import pandas as pd 
#Importamos numpy
import numpy as np 
#Importamos el archivo de soporte que contiene las funciones
import sys
sys.path.append('../')
from src.soporte import *
#Importamos datetime 
import datetime as dt 
print ("Librerias importadas")


Librerias importadas


Realizamos la lectura del fichero de data que transformamos en la anterior sesión:

In [10]:
df_preliminar = pd.read_csv("../clean_data/data_definitivo.csv")
df_preliminar.head()

Unnamed: 0   age        job  marital    education  default  housing  loan  \
0           0   NaN  housemaid  MARRIED     basic.4y      0.0      0.0   0.0   
1           1  57.0   services  MARRIED  high.school      NaN      0.0   0.0   
2           2  37.0   services  MARRIED  high.school      0.0      1.0   0.0   
3           3  40.0     admin.  MARRIED     basic.6y      0.0      0.0   0.0   
4           4  56.0   services  MARRIED  high.school      0.0      0.0   1.0   

     contact  duration  ...  latitude  longitude  \
0  telephone       261  ...    41.495    -71.233   
1  telephone       149  ...    34.601    -83.923   
2  telephone       226  ...    34.939    -94.847   
3  telephone       151  ...    49.041    -70.308   
4  telephone       307  ...    38.033   -104.463   

                                     id Count   Income Kidhome Teenhome  \
0  089b39d8-e4d0-461b-87d4-814d71e0e079      0  161770       1        0   
1  e9d37224-cb6f-4942-98d7-46672963d097      1   85477       1        1   
2  3f9f49b5-e410-4948-bf6e-f9244f04918b      2  147233       1        1   
3  9991fafb-4447-451a-8be2-b0df6098d13e      3  121393       1        2   
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb      4   63164       1        2   

           Dt_Customer NumWebVisitsMonth  Year  
0  2012-04-04 00:00:00                29  2012  
1  2012-12-30 00:00:00                 7  2012  
2  2012-02-02 00:00:00                 5  2012  
3  2012-12-21 00:00:00                29  2012  
4  2012-06-20 00:00:00                20  2012  

[5 rows x 31 columns]

Ejecutamos la función predefinida creada para hacer una primera visualización del dataset: 

In [11]:
visualizacion_1(df_preliminar)

DATOS GENERALES:
El dataframe está compuesto por 43000 filas y 31 columnas
-----------------------
Las columnas que conforman el dataframe son:
Index(['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y', 'date', 'latitude',
       'longitude', 'id', 'Count ', 'Income', 'Kidhome', 'Teenhome',
       'Dt_Customer', 'NumWebVisitsMonth', 'Year'],
      dtype='str')
-----------------------
Las columnas del df tienen la siguiente información
--
<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         43000 non-null  int64  
 1   age                37880 non-null  float64
 2   job                42655 non-null  str    
 3   marital     

Como podemos observar el dataframe está compuesto por 43000 filas y 31 columnas.
Algunas de las columnas del dataset requieren cambios en su denominación para dar más claridad al dataset. Para recordar que informaba cada columna, vamos a recuperar la definición anterior de las columnas:

- age: La edad del cliente.
- job: La ocupación o profesión del cliente.
- marital: El estado civil del cliente.
- education: El nivel educativo del cliente.
- default: Indica si el cliente tiene algún historial de incumplimiento de pagos (1: Sí, 0: No).
- housing: Indica si el cliente tiene un préstamo hipotecario (1: Sí, 0: No).
- loan: Indica si el cliente tiene algún otro tipo de préstamo (1: Sí, 0: No).
- contact: El método de contacto utilizado para comunicarse con el cliente.
- duration: La duración en segundos de la última interacción con el cliente.
- campaign: El número de contactos realizados durante esta campaña para este cliente.
- pdays: Número de días que han pasado desde la última vez que se contactó con el cliente durante esta campaña.
- previous: Número de veces que se ha contactado con el cliente antes de esta campaña.
- poutcome: Resultado de la campaña de marketing anterior.
- emp.var.rate: La tasa de variación del empleo.
- cons.price.idx: El índice de precios al consumidor.
- cons.conf.idx: El índice de confianza del consumidor.
- euribor3m: La tasa de interés de referencia a tres meses.
- nr.employed: El número de empleados.
- y: Indica si el cliente ha suscrito un producto o servicio (Sí/No).
- date: La fecha en la que se realizó la interacción con el cliente.
- contact_month: Mes en el que se realizó la interacción con el cliente durante la campaña de marketing.
- contact_year: Año en el que se realizó la interacción con el cliente durante la campaña de marketing.
- id: Un identificador único del cliente.
- Income: Representa el ingreso anual del cliente en términos monetarios.
- Kidhome: Indica el número de niños en el hogar del cliente.
- Teenhome: Indica el número de adolescentes en el hogar del cliente.
- Dt_Customer: Representa la fecha en que el cliente se convirtió en cliente de la empresa.
- NumWebVisitsMonth: Indica la cantidad de visitas mensuales del cliente al sitio web de la empresa.

In [12]:
#Antes de empezar a trabajar hacemos una copia del df_preliminar a uno de trabajo
df_work = df_preliminar.copy()
print("Se ha copiado el dataframe")

Se ha copiado el dataframe


***Cambio 1 --> Cambios de nombres de columnas***

Los cambios que vamos a realizar a las etiquetas de las columnas son los siguientes: 
- pdays = prev_contact
- previous = prev_calls
- poutcome = prev_result
- date = int_date
- Dt_Customer = cust_date
- y = suscribed

In [13]:
#Aplicamos la función para renombrar columnas sobre las columnas mencionadas previamente,
df_work = renombrar_columnas(df_work,'pdays', 'prev_contact')
df_work = renombrar_columnas(df_work, 'previous', 'prev_calls')
df_work = renombrar_columnas(df_work, 'poutcome', 'prev_result')
df_work = renombrar_columnas(df_work, 'date', 'int_date')
df_work = renombrar_columnas(df_work, 'Dt_Customer', 'cust_date')
df_work = renombrar_columnas(df_work, 'y', 'suscribed')
#Hacemos un .columns para comprobar que el cambio se haya ejecutado correctamente.
df_work.columns

Nombre de la columna cambiado de pdays a prev_contact
Nombre de la columna cambiado de previous a prev_calls
Nombre de la columna cambiado de poutcome a prev_result
Nombre de la columna cambiado de date a int_date
Nombre de la columna cambiado de Dt_Customer a cust_date
Nombre de la columna cambiado de y a suscribed


Index(['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'duration', 'campaign', 'prev_contact',
       'prev_calls', 'prev_result', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'suscribed', 'int_date',
       'latitude', 'longitude', 'id', 'Count ', 'Income', 'Kidhome',
       'Teenhome', 'cust_date', 'NumWebVisitsMonth', 'Year'],
      dtype='str')

***Cambio 2 --> Eliminación de columnas irrelevantes***

La columna Unnamed no aporta datos relevantes al estudio ya que es el número de registro en la tabla.

In [14]:
df_work.drop(columns= 'Unnamed: 0', inplace=True)
df_work.head()

age        job  marital    education  default  housing  loan    contact  \
0   NaN  housemaid  MARRIED     basic.4y      0.0      0.0   0.0  telephone   
1  57.0   services  MARRIED  high.school      NaN      0.0   0.0  telephone   
2  37.0   services  MARRIED  high.school      0.0      1.0   0.0  telephone   
3  40.0     admin.  MARRIED     basic.6y      0.0      0.0   0.0  telephone   
4  56.0   services  MARRIED  high.school      0.0      0.0   1.0  telephone   

   duration  campaign  ...  latitude  longitude  \
0       261         1  ...    41.495    -71.233   
1       149         1  ...    34.601    -83.923   
2       226         1  ...    34.939    -94.847   
3       151         1  ...    49.041    -70.308   
4       307         1  ...    38.033   -104.463   

                                     id  Count   Income Kidhome Teenhome  \
0  089b39d8-e4d0-461b-87d4-814d71e0e079       0  161770       1        0   
1  e9d37224-cb6f-4942-98d7-46672963d097       1   85477       1        1   
2  3f9f49b5-e410-4948-bf6e-f9244f04918b       2  147233       1        1   
3  9991fafb-4447-451a-8be2-b0df6098d13e       3  121393       1        2   
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb       4   63164       1        2   

             cust_date NumWebVisitsMonth  Year  
0  2012-04-04 00:00:00                29  2012  
1  2012-12-30 00:00:00                 7  2012  
2  2012-02-02 00:00:00                 5  2012  
3  2012-12-21 00:00:00                29  2012  
4  2012-06-20 00:00:00                20  2012  

[5 rows x 30 columns]

La columna count no aporta datos relevantes al estudio ya que es el número de registro en la tabla.

In [15]:
df_work.drop(columns= 'Count ', inplace=True)
df_work.head()

age        job  marital    education  default  housing  loan    contact  \
0   NaN  housemaid  MARRIED     basic.4y      0.0      0.0   0.0  telephone   
1  57.0   services  MARRIED  high.school      NaN      0.0   0.0  telephone   
2  37.0   services  MARRIED  high.school      0.0      1.0   0.0  telephone   
3  40.0     admin.  MARRIED     basic.6y      0.0      0.0   0.0  telephone   
4  56.0   services  MARRIED  high.school      0.0      0.0   1.0  telephone   

   duration  campaign  ...            int_date  latitude longitude  \
0       261         1  ...       2-agosto-2019    41.495   -71.233   
1       149         1  ...  14-septiembre-2016    34.601   -83.923   
2       226         1  ...     15-febrero-2019    34.939   -94.847   
3       151         1  ...   29-noviembre-2015    49.041   -70.308   
4       307         1  ...       29-enero-2017    38.033  -104.463   

                                     id  Income Kidhome Teenhome  \
0  089b39d8-e4d0-461b-87d4-814d71e0e079  161770       1        0   
1  e9d37224-cb6f-4942-98d7-46672963d097   85477       1        1   
2  3f9f49b5-e410-4948-bf6e-f9244f04918b  147233       1        1   
3  9991fafb-4447-451a-8be2-b0df6098d13e  121393       1        2   
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb   63164       1        2   

             cust_date NumWebVisitsMonth  Year  
0  2012-04-04 00:00:00                29  2012  
1  2012-12-30 00:00:00                 7  2012  
2  2012-02-02 00:00:00                 5  2012  
3  2012-12-21 00:00:00                29  2012  
4  2012-06-20 00:00:00                20  2012  

[5 rows x 29 columns]

***Cambio 3 --> Tratamiento de columnas en formato fecha***

In [16]:
df_work.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   age                37880 non-null  float64
 1   job                42655 non-null  str    
 2   marital            42915 non-null  str    
 3   education          41193 non-null  str    
 4   default            34019 non-null  float64
 5   housing            41974 non-null  float64
 6   loan               41974 non-null  float64
 7   contact            43000 non-null  str    
 8   duration           43000 non-null  int64  
 9   campaign           43000 non-null  int64  
 10  prev_contact       43000 non-null  int64  
 11  prev_calls         43000 non-null  int64  
 12  prev_result        43000 non-null  str    
 13  emp.var.rate       43000 non-null  float64
 14  cons.price.idx     42529 non-null  str    
 15  cons.conf.idx      43000 non-null  str    
 16  euribor3m          33744 non-null

Las columnas en formato fecha son int_date y Dt_customer por lo que vamos a visualizarlas para entender un poco como están pobladas.

In [17]:
df_work[['int_date']]

int_date
0           2-agosto-2019
1      14-septiembre-2016
2         15-febrero-2019
3       29-noviembre-2015
4           29-enero-2017
...                   ...
42995     13-octubre-2015
42996       17-marzo-2018
42997  15-septiembre-2016
42998  23-septiembre-2019
42999    6-noviembre-2019

[43000 rows x 1 columns]

**Tratamiento de la columna int_date**

En primer lugar dividimos la columna int_date en tres columnas:

In [18]:
df_work[["int_day", "int_month", "int_year"]] = df_work['int_date'].str.split("-", expand= True)
df_work.head()

age        job  marital    education  default  housing  loan    contact  \
0   NaN  housemaid  MARRIED     basic.4y      0.0      0.0   0.0  telephone   
1  57.0   services  MARRIED  high.school      NaN      0.0   0.0  telephone   
2  37.0   services  MARRIED  high.school      0.0      1.0   0.0  telephone   
3  40.0     admin.  MARRIED     basic.6y      0.0      0.0   0.0  telephone   
4  56.0   services  MARRIED  high.school      0.0      0.0   1.0  telephone   

   duration  campaign  ...                                    id  Income  \
0       261         1  ...  089b39d8-e4d0-461b-87d4-814d71e0e079  161770   
1       149         1  ...  e9d37224-cb6f-4942-98d7-46672963d097   85477   
2       226         1  ...  3f9f49b5-e410-4948-bf6e-f9244f04918b  147233   
3       151         1  ...  9991fafb-4447-451a-8be2-b0df6098d13e  121393   
4       307         1  ...  eca60b76-70b6-4077-80ba-bc52e8ebb0eb   63164   

  Kidhome  Teenhome            cust_date NumWebVisitsMonth  Year int_day  \
0       1         0  2012-04-04 00:00:00                29  2012       2   
1       1         1  2012-12-30 00:00:00                 7  2012      14   
2       1         1  2012-02-02 00:00:00                 5  2012      15   
3       1         2  2012-12-21 00:00:00                29  2012      29   
4       1         2  2012-06-20 00:00:00                20  2012      29   

    int_month int_year  
0      agosto     2019  
1  septiembre     2016  
2     febrero     2019  
3   noviembre     2015  
4       enero     2017  

[5 rows x 32 columns]

Sustituimos el mes en letra por el número de mes:

In [19]:
#Paso 1: Creamos un diccionario de tuplas con el mes y el número
meses = {
    'enero': '01',
    'febrero': '02',
    'marzo': '03',
    'abril': '04',
    'mayo': '05',
    'junio': '06',
    'julio': '07',
    'agosto': '08',
    'septiembre': '09',
    'octubre': '10',
    'noviembre': '11',
    'diciembre': '12'
}
#Paso 2 --> Utilizamos la función map para cambiar el nombre del mes por su número: 
df_work['int_month'] = df_work['int_month'].map(meses)
#Paso 3 --> Observamos el resultado obtenido: 
df_work['int_month']
    

0        08
1        09
2        02
3        11
4        01
         ..
42995    10
42996    03
42997    09
42998    09
42999    11
Name: int_month, Length: 43000, dtype: str

Ahora convertimos la columna int_day en una columna con dos dígitos.

In [20]:
#1. Creamos una lista vacía en la que volcaremos los resultados
days = []
#2. Creamos un bucle que recorra toda la columna:
for x in df_work['int_day']:
    if pd.isna(x):
         days.append(np.nan)  #Si encuentra un nulo lo devuelve como tal
    else:
        if int(x) < 10:
            days.append ("0" + str(x)) #Si el numero es menor que 10 le añade un 0
        else:
            days.append(str(x)) #Si no lo devuelve como tal 
df_work['int_day'] = days #Volcamos el resultado a la columna original

df_work['int_day'] 
            

0        02
1        14
2        15
3        29
4        29
         ..
42995    13
42996    17
42997    15
42998    23
42999    06
Name: int_day, Length: 43000, dtype: str

El último ajuste que hacemos es concatenar las fechas en una nueva columna.

In [21]:
#Vemos la cantidad de nulos en la columna int_date
nulos(df_work['int_date'])

La columna tiene 248 valores nulos


In [22]:
#Creamos una lista vacía en la que volcaremos los nuevos valores de la columna int_date
Nint = []
#Creamos una función que si encuentra nulos devuelva el nulo y si no la fecha concatenada: 
for i, x in enumerate(df_work['int_date']): #Accedemos a cada uno de los valores de la columna int_date
    #Si es nulo lo adjuntamos como nulo 
    if pd.isna(x):
        Nint.append(np.nan)
    else:
        #Accedemos a cada valor de las columnas day, month, year y los convertimos a string
        day = str(df_work.loc[i, 'int_day'])
        month = str(df_work.loc[i, 'int_month'])
        year = str(df_work.loc[i, 'int_year'])
        #Concatenamos los valores
        Nint.append(day + "-" + month + "-" + year)

#Convertimos la columna a formato datetime 
fechas = [] #Creamos de nuevo una lista vacía donde volcaremos las fechas 
for x in Nint:#Creamos un bucle que devuelva nulos y fechas
    if pd.isna(x):
        fechas.append(np.nan)
    else:
        fechas.append(pd.to_datetime(x, format = '%d-%m-%Y'))

#Volcamos la lista en una nueva columna del DF
df_work['new_int_date'] = fechas
#Verificamos el resultado y la cantidad de nulos para ver que esta no ha variado. 
print(df_work['new_int_date'])
nulos(df_work['new_int_date'])


0       2019-08-02
1       2016-09-14
2       2019-02-15
3       2015-11-29
4       2017-01-29
           ...    
42995   2015-10-13
42996   2018-03-17
42997   2016-09-15
42998   2019-09-23
42999   2019-11-06
Name: new_int_date, Length: 43000, dtype: datetime64[us]
La columna tiene 248 valores nulos


Por último, eliminamos todas las columnas auxiliares que hemos creado. 

In [23]:
df_work.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'prev_contact', 'prev_calls',
       'prev_result', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
       'euribor3m', 'nr.employed', 'suscribed', 'int_date', 'latitude',
       'longitude', 'id', 'Income', 'Kidhome', 'Teenhome', 'cust_date',
       'NumWebVisitsMonth', 'Year', 'int_day', 'int_month', 'int_year',
       'new_int_date'],
      dtype='str')

In [24]:
df_work.drop(columns= 'int_date',  inplace=True)
df_work.drop(columns= 'int_day', inplace=True)
df_work.drop(columns= 'int_month', inplace=True)
df_work.drop(columns= 'int_year', inplace=True)
df_work.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'prev_contact', 'prev_calls',
       'prev_result', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
       'euribor3m', 'nr.employed', 'suscribed', 'latitude', 'longitude', 'id',
       'Income', 'Kidhome', 'Teenhome', 'cust_date', 'NumWebVisitsMonth',
       'Year', 'new_int_date'],
      dtype='str')

**Tratamiento de la columna cust_date**

La columna cust_date y la columna year guardan relación ya que fue una columna utilizada para la unificación de las tres hojas del fichero excel en una sola hoja antes de la carga en excel, por tanto la eliminamos.

In [25]:
df_work.drop(columns= 'Year', inplace=True)
df_work.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'prev_contact', 'prev_calls',
       'prev_result', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
       'euribor3m', 'nr.employed', 'suscribed', 'latitude', 'longitude', 'id',
       'Income', 'Kidhome', 'Teenhome', 'cust_date', 'NumWebVisitsMonth',
       'new_int_date'],
      dtype='str')

In [26]:
#Visualizamos la columna de cust_date
df_work['cust_date']

0        2012-04-04 00:00:00
1        2012-12-30 00:00:00
2        2012-02-02 00:00:00
3        2012-12-21 00:00:00
4        2012-06-20 00:00:00
                ...         
42995     2014-03-08 0:00:00
42996     2014-03-11 0:00:00
42997     2014-09-18 0:00:00
42998     2014-05-17 0:00:00
42999     2014-09-29 0:00:00
Name: cust_date, Length: 43000, dtype: str

En esta columna vamos a eliminar los registros de horas y convertirlas a datetime.

In [27]:
#Comprobamos la cantidad de nulos en la columna
nulos(df_work['cust_date'])

La columna tiene 0 valores nulos


In [28]:
#Convertimos la columna a formato datetime
df_work['cust_date'] = pd.to_datetime(df_work['cust_date'])
print("La columna se ha convertido en formato datetime")

La columna se ha convertido en formato datetime


In [29]:
#Eliminamos la parte de la hora 
df_work['cust_date'] = df_work['cust_date'].dt.date
df_work['cust_date']

0        2012-04-04
1        2012-12-30
2        2012-02-02
3        2012-12-21
4        2012-06-20
            ...    
42995    2014-03-08
42996    2014-03-11
42997    2014-09-18
42998    2014-05-17
42999    2014-09-29
Name: cust_date, Length: 43000, dtype: object

***Cambio 4 --> Ajuste de las columnas con numeros enteros pero llevan decimales***

**- Tratamiento de la columna age**

La columna age presenta decimales en los años lo que nos es indiferente en nuestro análisis por lo que vamos a eliminarlos. 

In [30]:
#Visualizamos la columna
df_work['age']


0         NaN
1        57.0
2        37.0
3        40.0
4        56.0
         ... 
42995     NaN
42996    34.0
42997     NaN
42998     NaN
42999     NaN
Name: age, Length: 43000, dtype: float64

In [31]:
#Visualizamos la cantidad de nulos 
nulos(df_work['age'])

La columna tiene 5120 valores nulos


In [32]:
#Realizamos la conversión de los valores con una función lambda
df_work['age'] = convertir_numero_entero(df_work['age'])

In [33]:
#Comprobamos los nulos de nuevo 
nulos(df_work['age'])

La columna tiene 5120 valores nulos


***Cambio 5 --> Conversión de columnas binarias a si/no***

En nuestro dataframe, encontramos varias columnas que utilizan código binario para indicar si un cliente cuenta con algunos servicios o no. Vamos a convertir ese código binario a si o no. Las columnas son: 
- Default
- Housing 
- Loan 

Estas utilizan 1 para indicar que un cliente tiene un servicio y un 0 si no lo tiene

In [34]:
df_work[['housing', 'loan', 'default']]

housing  loan  default
0          0.0   0.0      0.0
1          0.0   0.0      NaN
2          1.0   0.0      0.0
3          0.0   0.0      0.0
4          0.0   1.0      0.0
...        ...   ...      ...
42995      0.0   0.0      0.0
42996      1.0   1.0      0.0
42997      1.0   0.0      0.0
42998      0.0   0.0      NaN
42999      0.0   1.0      0.0

[43000 rows x 3 columns]

**Tratamiento de la columna housing**

En primer lugar comprobamos la cantidad de nulos en la columna:

In [35]:
nulos(df_work['housing'])

La columna tiene 1026 valores nulos


Comprobamos que no haya más valores que esos 3:

In [36]:
df_work['housing'].unique()

array([ 0.,  1., nan])

In [37]:
#Ejecutamos la función creada para convertir valores binarios en yes o no.
df_work['housing'] = binario_to_bool(df_work['housing'])

In [38]:
#Volvemos a ejecutar los nulos para ver que no han cambiado
nulos(df_work['housing'])

La columna tiene 1026 valores nulos


**Tratamiento de las columnas loan y default**

Vamos a replicar el proceso anterior pero para estas dos columnas ahora. 

- loan

In [39]:
#Comprobamos los nulos de la columna loan
nulos(df_work['loan'])

La columna tiene 1026 valores nulos


In [40]:
df_work['loan'].unique()

array([ 0.,  1., nan])

In [41]:
#Ejecutamos la función
df_work['loan'] = binario_to_bool(df_work['loan'])

In [42]:
#Volvemos a comprobar los nulos 
nulos(df_work['loan'])

La columna tiene 1026 valores nulos


- default

In [43]:
#Comprobamos los nulos 
nulos(df_work['default'])

La columna tiene 8981 valores nulos


In [44]:
df_work['default'].unique()

array([ 0., nan,  1.])

In [45]:
#Ejecutamos el cambio 
df_work['default'] = binario_to_bool(df_work['default'])

In [46]:
#Comprobamos los nulos de nuevo
nulos(df_work['default'])

La columna tiene 8981 valores nulos


Por último vamos a observar el resultado final tras aplicar los cambios en dichas columnas

In [47]:
df_work[['housing', 'loan', 'default']]

housing loan default
0          no   no      no
1          no   no     NaN
2         yes   no      no
3          no   no      no
4          no  yes      no
...       ...  ...     ...
42995      no   no      no
42996     yes  yes      no
42997     yes   no      no
42998      no   no     NaN
42999      no  yes      no

[43000 rows x 3 columns]

***Cambio 6 --> Análisis + limpieza de columnas restantes***

In [48]:
df_work.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'prev_contact', 'prev_calls',
       'prev_result', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
       'euribor3m', 'nr.employed', 'suscribed', 'latitude', 'longitude', 'id',
       'Income', 'Kidhome', 'Teenhome', 'cust_date', 'NumWebVisitsMonth',
       'new_int_date'],
      dtype='str')

In [49]:
df_work.head()

age        job  marital    education default housing loan    contact  \
0  <NA>  housemaid  MARRIED     basic.4y      no      no   no  telephone   
1    57   services  MARRIED  high.school     NaN      no   no  telephone   
2    37   services  MARRIED  high.school      no     yes   no  telephone   
3    40     admin.  MARRIED     basic.6y      no      no   no  telephone   
4    56   services  MARRIED  high.school      no      no  yes  telephone   

   duration  campaign  ...  suscribed  latitude longitude  \
0       261         1  ...         no    41.495   -71.233   
1       149         1  ...         no    34.601   -83.923   
2       226         1  ...         no    34.939   -94.847   
3       151         1  ...         no    49.041   -70.308   
4       307         1  ...         no    38.033  -104.463   

                                     id  Income Kidhome Teenhome   cust_date  \
0  089b39d8-e4d0-461b-87d4-814d71e0e079  161770       1        0  2012-04-04   
1  e9d37224-cb6f-4942-98d7-46672963d097   85477       1        1  2012-12-30   
2  3f9f49b5-e410-4948-bf6e-f9244f04918b  147233       1        1  2012-02-02   
3  9991fafb-4447-451a-8be2-b0df6098d13e  121393       1        2  2012-12-21   
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb   63164       1        2  2012-06-20   

  NumWebVisitsMonth  new_int_date  
0                29    2019-08-02  
1                 7    2016-09-14  
2                 5    2019-02-15  
3                29    2015-11-29  
4                20    2017-01-29  

[5 rows x 28 columns]

In [50]:
df_work[['prev_contact', 'prev_calls', 'prev_result', 'emp.var.rate', 'cons.price.idx', 'euribor3m', 'nr.employed']]

prev_contact  prev_calls  prev_result  emp.var.rate cons.price.idx  \
0               999           0  NONEXISTENT           1.1         93,994   
1               999           0  NONEXISTENT           1.1         93,994   
2               999           0  NONEXISTENT           1.1         93,994   
3               999           0  NONEXISTENT           1.1         93,994   
4               999           0  NONEXISTENT           1.1         93,994   
...             ...         ...          ...           ...            ...   
42995           999           0  NONEXISTENT           1.4         93,444   
42996           999           0  NONEXISTENT          -0.1           93,2   
42997           999           0  NONEXISTENT           1.4         93,918   
42998           999           0  NONEXISTENT           1.4         93,918   
42999           999           0  NONEXISTENT          -0.1           93,2   

      euribor3m nr.employed  
0         4,857        5191  
1           NaN        5191  
2         4,857        5191  
3           NaN        5191  
4           NaN        5191  
...         ...         ...  
42995       NaN      5228,1  
42996       NaN      5195,8  
42997       NaN      5228,1  
42998     4,958      5228,1  
42999     4,021      5195,8  

[43000 rows x 7 columns]

**- Columna job**

In [51]:
#Analizamos los valores para ver que todo cuadra
df_work['job'].unique()

<StringArray>
[    'housemaid',      'services',        'admin.',   'blue-collar',
    'technician',       'retired',    'management',    'unemployed',
 'self-employed',             nan,  'entrepreneur',       'student']
Length: 12, dtype: str

La columna no requiere mayor limpieza por ahora

**- Columna marital**

In [52]:
#Analizamos los valores para ver que todo cuadra
df_work['marital'].unique()

<StringArray>
['MARRIED', 'SINGLE', 'DIVORCED', nan]
Length: 4, dtype: str

La columna no requiere mayor limpieza por ahora

**- Columna education**

In [53]:
#Analizamos los valores para ver que todo cuadra
df_work['education'].unique()

<StringArray>
[           'basic.4y',         'high.school',            'basic.6y',
            'basic.9y', 'professional.course',                   nan,
   'university.degree',          'illiterate']
Length: 8, dtype: str

**- Columna duration**

In [54]:
df_work['duration'].unique()

array([ 261,  149,  226, ..., 1246, 1556, 1868], shape=(1540,))

Esta columna como hemos visto previamente nos indicaba la duración de la llamada con el cliente en segundos, para hacer los datos más visuales y evitar valores muy extremos a posteriori vamos a convertir la duración a minutos. 

In [55]:
#Comprobamos los nulos
nulos(df_work['duration'])

La columna tiene 0 valores nulos


In [56]:
#Ejecutamos el cambio aplicando una función
df_work['duration'] = segundos_a_minutos(df_work['duration'])

In [57]:
#Comprobamos el resultado 
df_work['duration']

0         4.350000
1         2.483333
2         3.766667
3         2.516667
4         5.116667
           ...    
42995    10.300000
42996     0.700000
42997     6.516667
42998    11.233333
42999     1.733333
Name: duration, Length: 43000, dtype: float64

In [58]:
#Ahora vamos a revisar las duraciones máximas y minimas 
valor_max = df_work['duration'].max().round(2)
valor_min = df_work['duration'].min().round(2)
print (f'La duración máxima de una llamada fue de {valor_max} mins y la duración mínima de {valor_min} mins')

La duración máxima de una llamada fue de 81.97 mins y la duración mínima de 0.0 mins


Como vemos hay valores que no son realistas en los registros ya que una llamada de 0 segundos no tiene sentido a la vez que una llamada de 82 minutos tampoco lo tiene. Por lo que vamos a aplicar un pequeño filtro a la columna convirtiendo a nulos todas aquellas llamadas mayores a 30 minutos e inferiores a 1 minuto para obtener resultados más realistas.

In [59]:
mayores_20 = (df_work['duration'] > 20).sum()
menores_1 = (df_work['duration'] < 1).sum()
valores_a_cambiar = mayores_20 + menores_1
print (f'Hay {mayores_20} registros superiores a 20 mins y {menores_1} registros inferiores a 1 min')
print (f'Vamos a cambiar {valores_a_cambiar} valores')

Hay 533 registros superiores a 20 mins y 4356 registros inferiores a 1 min
Vamos a cambiar 4889 valores


In [60]:
#Creamos una función lambda para hacer el cambio
df_work['duration'] = df_work['duration'].apply(lambda x: np.nan if x > 20 or x < 1 else x)
print("Se ha aplicado la corrección")

Se ha aplicado la corrección


In [61]:
#Una vez ejecutada la función comprobamos los nulos 
nulos(df_work['duration'])

La columna tiene 4889 valores nulos


**- Columna campaign**

In [62]:
df_work['campaign'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 19, 18, 23, 14,
       22, 25, 16, 17, 15, 20, 56, 39, 35, 42, 28, 26, 27, 32, 21, 24, 29,
       31, 30, 41, 37, 40, 33, 34, 43])

En esta columna podríamos eliminar todos los registros superiore a 31 ya que implicarían más de un contacto diario, pero en este caso los vamos a mantener ya que no conocemos la naturaleza de cada una de las llamadas realizadas.

**- Columna suscribed**

In [63]:
df_work['suscribed'].unique()

<StringArray>
['no', 'yes']
Length: 2, dtype: str

La columna no necesita mayor limpieza por el momento

**- Columnas latitude y longitude**

Estas dos columnas nos hablan de la posición geográfica de nuestro cliente lo que es irrelevante para nuestro estudio. Por tanto las borraremos de nuestro dataframe. 

In [64]:
df_work.drop(columns= 'latitude', inplace=True)
df_work.drop(columns= 'longitude', inplace=True)
df_work.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'prev_contact', 'prev_calls',
       'prev_result', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
       'euribor3m', 'nr.employed', 'suscribed', 'id', 'Income', 'Kidhome',
       'Teenhome', 'cust_date', 'NumWebVisitsMonth', 'new_int_date'],
      dtype='str')

**- Columna Kidhome**

In [65]:
df_work['Kidhome'].unique()

array([1, 0, 2])

La columna no necesita mayor limpieza por el momento

**- Columna Teenhome**

In [66]:
df_work['Teenhome'].unique()

array([0, 1, 2])

La columna no necesita mayor limpieza por el momento

**-Columna NumWebVisitsMonth**

In [67]:
df_work['NumWebVisitsMonth'].unique()

array([29,  7,  5, 20, 26,  3, 21, 18,  9, 30, 32, 27, 15, 28,  2, 17, 12,
        1, 25, 10, 14, 24, 13, 11,  8, 23, 16,  4, 31, 19, 22,  6])

La columna no necesita mayor limpieza por el momento

**- Columna prev_contact**

In [68]:
df_work['prev_contact'].unique()

array([999,   6,   4,   3,   5,   1,   0,  10,   7,   8,   9,  11,   2,
        12,  13,  14,  15,  16,  21,  17,  18,  22,  25,  26,  19,  27,
        20])

Como vemos hay valores que indican que hubo 999 contactos en un mes con el cliente lo que no es realista por lo que los vamos a convertir en nulos. 

In [69]:
valores_elim = (df_work['prev_contact'] == 999).sum()
print (f'Vamos a convertir {valores_elim} valores a nulos')

Vamos a convertir 41412 valores a nulos


In [70]:
#Aplicamos una función lambda para convertir los valores a nulos
df_work['prev_contact'] = df_work['prev_contact'].apply(lambda x: np.nan if x == 999 else x)

In [71]:
#Comprobamos la cantidad de nulos
nulos(df_work['prev_contact'])

La columna tiene 41412 valores nulos


**- Columna prev_calls**

In [72]:
df_work['prev_calls'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7])

La columna no requiere de mayor limpieza por el momento

**- Columna prev_result**

In [73]:
df_work['prev_result'].unique()

<StringArray>
['NONEXISTENT', 'FAILURE', 'SUCCESS']
Length: 3, dtype: str

La columna no requiere de mayor limpieza por el momento

No parece que la columna requiera limpieza

**- Columna contact**

In [74]:
#Analizamos los valores para ver que todo cuadra
df_work['contact'].unique()

<StringArray>
['telephone', 'cellular']
Length: 2, dtype: str

Esta columna lo único que diferencia es el contacto fue por telefono fijo o telefono móvil por lo que los datos que nos ofrece aportan poco a nuestro estudio ya que el contacto es prácticamente el mismo. Por tanto nos deshacemos de la columna. 

In [75]:
#Utilizamos la fórmula drop para deshacernos de la columna
df_work.drop(columns= 'contact', inplace=True)
print("Columna eliminada")

Columna eliminada


In [76]:
df_work.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'duration', 'campaign', 'prev_contact', 'prev_calls', 'prev_result',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'suscribed', 'id', 'Income', 'Kidhome', 'Teenhome',
       'cust_date', 'NumWebVisitsMonth', 'new_int_date'],
      dtype='str')

**- Columna emp.var.rate**

In [77]:
df_work['emp.var.rate'].unique()

array([ 1.1,  1.4, -0.1, -0.2, -1.8, -2.9, -3.4, -3. , -1.7, -1.1])

La columna no requiere limpieza adicional por el momento

**- Columna cons.price.idx**

In [78]:
df_work['cons.price.idx'].unique()

<StringArray>
['93,994',      nan, '94,465', '93,918', '93,444', '93,798',   '93,2',
 '92,756', '92,843', '93,075', '92,893', '92,963', '92,469', '92,201',
 '92,379', '92,431', '92,649', '92,713', '93,369', '93,749', '93,876',
 '94,055', '94,215', '94,027', '94,199', '94,601', '94,767']
Length: 27, dtype: str

In [79]:
nulos(df_work['cons.price.idx'])

La columna tiene 471 valores nulos


Esta columna tiene un problema y es que utiliza comas donde debería utilizar . lo que puede llevar a python a confusiones.

In [84]:
#Comprobamos el tipo de columna.
df_work['cons.price.idx'].dtype

<StringDtype(storage='python', na_value=nan)>

In [ ]:
#Aplicamos una formula creada para este propósito.
df_work['cons.price.idx'] = comas_por_puntos(df_work['cons.price.idx'])

In [ ]:
#Comprobamos que el resultado sea correcto. 
nulos(df_work['cons.price.idx'])
df_work['cons.price.idx'].unique()

La columna tiene 471 valores nulos


array([93.994,    nan, 94.465, 93.918, 93.444, 93.798, 93.2  , 92.756,
       92.843, 93.075, 92.893, 92.963, 92.469, 92.201, 92.379, 92.431,
       92.649, 92.713, 93.369, 93.749, 93.876, 94.055, 94.215, 94.027,
       94.199, 94.601, 94.767])

**- Columna Euribor3m**

Esta columna requiere de cambios como los que hemos hecho anteriormente.

In [ ]:
#Comprobamos los nulos 
nulos(df_work['euribor3m'])

La columna tiene 9256 valores nulos


In [ ]:
#Comprobamos el tipo de columna que es
df_work['euribor3m'].dtype

dtype('O')

In [ ]:
#Aplicamos la formula que hemos definido previamente
df_work['euribor3m'] = comas_por_puntos(df_work['euribor3m'])

In [ ]:
#Comprobamos los nulos y el resultado
nulos(df_work['euribor3m'])
df_work['euribor3m']

La columna tiene 9256 valores nulos


0        4.857
1          NaN
2        4.857
3          NaN
4          NaN
         ...  
42995      NaN
42996      NaN
42997      NaN
42998    4.958
42999    4.021
Name: euribor3m, Length: 43000, dtype: float64

Con esto concluimos la limpieza por lo que exportamos el dataframe limpio a un nuevo csv para utilizarlo en un Jupyter nuevo. 

In [ ]:
df_work.to_csv("data_limpio", index = False)
print("dataframe exportado")

dataframe exportado
